agent: Agent.class AtomicSentence.class ComplexSentence.class Conclusion.class DefiniteClause.class KnowledgeBase.class Premise.class Query.class Sentence.class Substitution.class

run: Agent.class
	java Agent

Agent.class: Agent.java
	javac Agent.java

AtomicSentence.class: AtomicSentence.java
	javac AtomicSentence.java

ComplexSentence.class: ComplexSentence.java
	javac ComplexSentence.java

Conclusion.class: Conclusion.java
	javac Conclusion.java

DefiniteClause.class: DefiniteClause.java
	javac DefiniteClause.java

KnowledgeBase.class: KnowledgeBase.java
	javac KnowledgeBase.java

Premise.class: Premise.java
	javac Premise.java

Query.class: Query.java
	javac Query.java

Sentence.class: Sentence.java
	javac Sentence.java

Substitution.class: Substitution.java
	javac Substitution.java